theme: jekyll-theme-minimal
title: <p align="center" style="color:#000FF;">HollowInk</p>
description: Jogar junto é sempre mais gostoso!
logo: "https://media.discordapp.net/attachments/637764934196789279/809258333318938644/logomarca.png"
