theme: jekyll-theme-minimal
title: <p align="center">HollowInk</p>
description: <a href="#-introdução">🚩 INTRODUÇÃO</a>&#013;<a href="#--regras">🚩 REGRAS</a>
show_downloads: false
logo: "https://i.imgur.com/QFu1fC5.png"
